业务系统：分销结算/其他支出核销表，单据号00017713，这条在老KA，品种是银黄口服液，业务系统是授信压款，请检查这条单据

select bod_id,bod_cd,creat_dt,med_id from tb_bill where bod_type_id=36 and bod_cd='00017713'

update tb_bill set med_id=4475 where bod_id=4858781 

4858781

select * from tb_medicine where med_id=4717 4475

select bod_id,bod_cd,creat_dt,med_id from tb_bill where bod_type_id=36 and bod_cd='00017713'

select c.bod_id,b.dtl_id,h.rec_id,b.med_id,d.qty,b.price,b.amot,carry_dt1=c.carry_dt,c.bod_cd,d.sta_id,broker=dbo.fn_staff_name(case when h.sta_id is null then d.sta_id else h.sta_id end),mate_name=dbo.fn_mate_name(c.dst_id), d.bat_cd,e.price1,d.price3,med_code,m.material_code,med_name,chm_name,specifi,pdt_place,med_unit=dbo.fn_obj_desc(m.unit_id),med_type=dbo.fn_med_type(m.med_id),e.type_id2 from tb_bill_dtl b inner join tb_bill_stadtl h on b.med_id=h.rec_id left join tb_bill_dtl d on d.dtl_id=h.dtl_id left join tb_bill c on c.bod_id=d.bod_id left join tb_medicine m on d.med_id=m.med_id left join (select i.rec_id,i.type_id2,i.price1,j.sta_id,j.rate from tb_brokermed i inner join tb_brokermedtl j on i.rec_id=j.rela_id) e  on e.rec_id =dbo.fn_getbrokermedrecid(c.src_id,c.dst_id,d.med_id,c.carry_dt) and e.sta_id=h.sta_id where b.bod_id=19645

select a.*,b.mate_name,mate_name1=c.mate_name,creater=d.zname,checker=e.zname,broker=f.zname,f.stoppay,carryer=g.zname,receiver=h.zname,storager=i.zname ,bod_cd1=dbo.fn_getbodcd1(a.bod_id),a.channel_id,channel=dbo.fn_obj_desc(a.channel_id),a.channel_dtl_id,channel_dtl=dbo.fn_obj_desc(a.channel_dtl_id) 
from tb_bill a 
left join tb_busimate b on a.src_id =b.mate_id 
left join tb_busimate c on a.dst_id =c.mate_id 
left join tb_staff d on a.creat_by =d.sta_id 
left join tb_staff e on a.check_by =e.sta_id 
left join tb_staff f on a.broker_id =f.sta_id 
left join tb_staff g on a.carry_by =g.sta_id 
left join tb_staff h on a.receipt_by =h.sta_id 
left join tb_staff i on a.storage_by =i.sta_id 
where a.bod_type_id=57  and a.creat_dt>= '2025-07-01' and a.creat_dt< dateadd(day,1,'2025-07-16')

select top 10 b.bod_id,b.dtl_id,h.* from tb_bill a
 inner join tb_bill_dtl b on a.bod_id=b.bod_id
 left join tb_bill_stadtl h on b.dtl_id=h.dtl_id
 where a.bod_type_id=2

 tb_bill_stadtl h where a.bod_id=h.bod_id and a.bod_type_id=2

insert into tb_bill_stadtl (bod_id,dtl_id) 
select b.bod_id,b.dtl_id from tb_bill a,tb_bill_dtl b where bod_type_id=57  and a.bod_id=b.bod_id
	and not exists (select 1 from tb_bill_stadtl h where b.bod_id=h.bod_id and b.dtl_id=h.dtl_id)





 select a.rec_id,a.ckd_amot3,y.* from tb_bill_stadtl a inner join (
 
 select h.rec_id,b.dtl_id,a.bod_id,a.bod_type_id,a.busi_type,a.bod_cd,creat_dt=cast(convert(char(10),a.carry_dt,20) as datetime),a.bod_desc, d.type_id2,d.price1,b.price3, e.mate_name,mate_name1=f.mate_name, b.lead_id,leader=k.BU_SORT1,department=k.VKBUR_TXT,sta_id=case when h.sta_id is null then b.sta_id else h.sta_id end, broker=c.zname,cdistrict=dbo.fn_getdistrict1(e.district),receiver1=c.receiver,c.bank_name,c.depo_acco, b.med_id,m.material_code,m.med_code,m.med_name,m.specifi,m.pdt_place,med_unit=dbo.fn_obj_desc(m.unit_id),m.type_id1, b.bat_cd,amot=cast(d.rate*b.qty as decimal(15,2)), b.qty,rate=cast(d.rate as decimal(15,4)), rate2=cast(case when isnull(d.price1,0)=0 then 0 else 100.00*d.rate/d.price1 end as decimal(10,2)), y.ckd_amot,j.amot1,j.amot2,h.ckd_amot3 ,b.channel_id,channel=dbo.fn_obj_desc1(11,b.channel_id),b.channel_dtl_id,channel_dtl=dbo.fn_obj_desc1(12,b.channel_dtl_id) from tb_bill a inner join tb_bill_dtl b on a.bod_id=b.bod_id left join tb_bill_stadtl h on b.dtl_id=h.dtl_id left join tb_staff c on c.sta_id=case when h.sta_id is null then b.sta_id else h.sta_id end inner join tb_busimate e on a.dst_id=e.mate_id left  join tb_busimate f on a.src_id=f.mate_id inner join tb_medicine m on b.med_id=m.med_id left join (select i.rec_id,i.type_id2,i.price1,j.sta_id,j.rate from tb_brokermed i inner join tb_brokermedtl j on i.rec_id=j.rela_id) d on d.rec_id =dbo.fn_getbrokermedrecid(a.src_id,a.dst_id,b.med_id,a.carry_dt) and d.sta_id=h.sta_id left join SAP_ZSD_BUS k on k.rec_id=dbo.fn_getSAP_ZSD_BUSrecid(b.channel_id,b.channel_dtl_id,e.district,e.mate_code,m.material_code1,a.carry_dt) left join (select b.med_id,amot1=sum(cast(isnull(b.amot,0) as decimal(15,2))),amot2=sum(case a.bod_status_id when 1 then 1 else 0 end*cast(isnull(b.amot,0) as decimal(15,2))) from tb_bill a,tb_bill_dtl b where a.bod_type_id=17  and a.bod_id=b.bod_id and b.med_id>0 group by b.med_id) j on h.rec_id=j.med_id left join (select b.med_id,ckd_amot=sum(cast(b.amot as decimal(15,2))) from tb_bill a,tb_bill_dtl b where a.bod_type_id=17 and a.bod_status_id=1  and a.bod_id=b.bod_id 	and exists (select 1 from tb_bill c,tb_bill_dtl d where c.bod_type_id=18 and c.bod_status_id=1 and c.creat_dt>= '2025-01-01' and c.bod_id=d.bod_id and d.med_id=a.bod_id) group by b.med_id) y on h.rec_id=y.med_id where a.bod_type_id=2 and a.bod_status_id=1 and e.mate_type_id=1   and a.carry_dt>= '2025-01-01' and a.carry_dt< dateadd(day,1,'2025-07-16') and (h.rate<>0 or b.rate<>0) 
 union all 
 select h.rec_id,dtl_id=0,a.bod_id,a.bod_type_id,busi_type=0,a.bod_cd,creat_dt=cast(convert(char(10),a.carry_dt,20) as datetime),a.bod_desc, type_id2=0,price1=0,price3=0, mate_name=dbo.fn_mate_name(a.dst_id),mate_name1=f.mate_name, lead_id=0,leader='',department='',sta_id=a.broker_id,broker=c.zname,cdistrict=dbo.fn_getdistrict(c.district),receiver1=c.receiver,c.bank_name,c.depo_acco, a.med_id,m.material_code,m.med_code,m.med_name,m.specifi,m.pdt_place,med_unit=dbo.fn_obj_desc(m.unit_id),m.type_id1, bat_cd='',amot=cast(a.bod_amot as decimal(15,2)),qty=0,rate=0,rate2=0.00,y.ckd_amot,j.amot1,j.amot2,h.ckd_amot3 ,a.channel_id,channel=dbo.fn_obj_desc1(11,a.channel_id),a.channel_dtl_id,channel_dtl=dbo.fn_obj_desc1(12,a.channel_dtl_id) from tb_bill a left join tb_bill_stadtl h on a.bod_id=h.bod_id inner join tb_staff c on a.broker_id=c.sta_id left join tb_busimate f on a.src_id=f.mate_id left join tb_medicine m on a.med_id=m.med_id left join (select b.sta_id,amot1=sum(cast(isnull(b.amot,0) as decimal(15,2))),amot2=sum(case a.bod_status_id when 1 then 1 else 0 end*cast(isnull(b.amot,0) as decimal(15,2))) 	from tb_bill a,tb_bill_dtl b where a.bod_type_id=17  and a.bod_id=b.bod_id and b.sta_id>0 group by b.sta_id) j on a.bod_id=j.sta_id left join (select b.sta_id,ckd_amot=sum(b.amot) from tb_bill a,tb_bill_dtl b where a.bod_type_id=17 and a.bod_status_id=1 and a.creat_dt>= '2025-01-01'  and a.bod_id=b.bod_id 	and exists (select 1 from tb_bill c,tb_bill_dtl d where c.bod_type_id=18 and c.bod_status_id=1 and c.creat_dt>= '2025-01-01' and c.bod_id=d.bod_id and d.med_id=a.bod_id) group by b.sta_id) y on a.bod_id=y.sta_id where a.bod_type_id=19 and a.bod_status_id=1 and a.comp_id=1  and a.carry_dt>= '2025-01-01' and a.carry_dt< dateadd(day,1,'2025-07-16')
 
 ) y on a.rec_id=y.rec_id

 select a.rec_id,a.ckd_amot3,y.* from tb_bill_stadtl a inner join (
 
 select h.rec_id,b.dtl_id,a.bod_id,a.bod_type_id,a.busi_type,a.bod_cd,creat_dt=cast(convert(char(10),a.carry_dt,20) as datetime),a.bod_desc, d.type_id2,d.price1,b.price3, e.mate_name,mate_name1=f.mate_name, b.lead_id,leader=k.BU_SORT1,department=k.VKBUR_TXT,sta_id=case when h.sta_id is null then b.sta_id else h.sta_id end, broker=c.zname,cdistrict=dbo.fn_getdistrict1(e.district),receiver1=c.receiver,c.bank_name,c.depo_acco, b.med_id,m.material_code,m.med_code,m.med_name,m.specifi,m.pdt_place,med_unit=dbo.fn_obj_desc(m.unit_id),m.type_id1, b.bat_cd,amot=cast(d.rate*b.qty as decimal(15,2)), b.qty,rate=cast(d.rate as decimal(15,4)), rate2=cast(case when isnull(d.price1,0)=0 then 0 else 100.00*d.rate/d.price1 end as decimal(10,2)), y.ckd_amot,j.amot1,j.amot2,h.ckd_amot3 ,b.channel_id,channel=dbo.fn_obj_desc1(11,b.channel_id),b.channel_dtl_id,channel_dtl=dbo.fn_obj_desc1(12,b.channel_dtl_id) from tb_bill a inner join tb_bill_dtl b on a.bod_id=b.bod_id left join tb_bill_stadtl h on b.dtl_id=h.dtl_id left join tb_staff c on c.sta_id=case when h.sta_id is null then b.sta_id else h.sta_id end inner join tb_busimate e on a.dst_id=e.mate_id left  join tb_busimate f on a.src_id=f.mate_id inner join tb_medicine m on b.med_id=m.med_id left join (select i.rec_id,i.type_id2,i.price1,j.sta_id,j.rate from tb_brokermed i inner join tb_brokermedtl j on i.rec_id=j.rela_id) d on d.rec_id =dbo.fn_getbrokermedrecid(a.src_id,a.dst_id,b.med_id,a.carry_dt) and d.sta_id=h.sta_id left join SAP_ZSD_BUS k on k.rec_id=dbo.fn_getSAP_ZSD_BUSrecid(b.channel_id,b.channel_dtl_id,e.district,e.mate_code,m.material_code1,a.carry_dt) left join (select b.med_id,amot1=sum(cast(isnull(b.amot,0) as decimal(15,2))),amot2=sum(case a.bod_status_id when 1 then 1 else 0 end*cast(isnull(b.amot,0) as decimal(15,2))) from tb_bill a,tb_bill_dtl b where a.bod_type_id=17  and a.bod_id=b.bod_id and b.med_id>0 group by b.med_id) j on h.rec_id=j.med_id left join (select b.med_id,ckd_amot=sum(cast(b.amot as decimal(15,2))) from tb_bill a,tb_bill_dtl b where a.bod_type_id=17 and a.bod_status_id=1  and a.bod_id=b.bod_id 	and exists (select 1 from tb_bill c,tb_bill_dtl d where c.bod_type_id=18 and c.bod_status_id=1 and c.creat_dt>= '2025-01-01' and c.bod_id=d.bod_id and d.med_id=a.bod_id) group by b.med_id) y on h.rec_id=y.med_id where a.bod_type_id=2 and a.bod_status_id=1 and e.mate_type_id=1   and a.carry_dt>= '2025-01-01' and a.carry_dt< dateadd(day,1,'2025-07-16') and (h.rate<>0 or b.rate<>0) 
 union all 
 select h.rec_id,dtl_id=0,a.bod_id,a.bod_type_id,busi_type=0,a.bod_cd,creat_dt=cast(convert(char(10),a.carry_dt,20) as datetime),a.bod_desc, type_id2=0,price1=0,price3=0, mate_name=dbo.fn_mate_name(a.dst_id),mate_name1=f.mate_name, lead_id=0,leader='',department='',sta_id=a.broker_id,broker=c.zname,cdistrict=dbo.fn_getdistrict(c.district),receiver1=c.receiver,c.bank_name,c.depo_acco, a.med_id,m.material_code,m.med_code,m.med_name,m.specifi,m.pdt_place,med_unit=dbo.fn_obj_desc(m.unit_id),m.type_id1, bat_cd='',amot=cast(a.bod_amot as decimal(15,2)),qty=0,rate=0,rate2=0.00,y.ckd_amot,j.amot1,j.amot2,h.ckd_amot3 ,a.channel_id,channel=dbo.fn_obj_desc1(11,a.channel_id),a.channel_dtl_id,channel_dtl=dbo.fn_obj_desc1(12,a.channel_dtl_id) from tb_bill a left join tb_bill_stadtl h on a.bod_id=h.bod_id inner join tb_staff c on a.broker_id=c.sta_id left join tb_busimate f on a.src_id=f.mate_id left join tb_medicine m on a.med_id=m.med_id left join (select b.sta_id,amot1=sum(cast(isnull(b.amot,0) as decimal(15,2))),amot2=sum(case a.bod_status_id when 1 then 1 else 0 end*cast(isnull(b.amot,0) as decimal(15,2))) 	from tb_bill a,tb_bill_dtl b where a.bod_type_id=17  and a.bod_id=b.bod_id and b.sta_id>0 group by b.sta_id) j on a.bod_id=j.sta_id left join (select b.sta_id,ckd_amot=sum(b.amot) from tb_bill a,tb_bill_dtl b where a.bod_type_id=17 and a.bod_status_id=1 and a.creat_dt>= '2025-01-01'  and a.bod_id=b.bod_id 	and exists (select 1 from tb_bill c,tb_bill_dtl d where c.bod_type_id=18 and c.bod_status_id=1 and c.creat_dt>= '2025-01-01' and c.bod_id=d.bod_id and d.med_id=a.bod_id) group by b.sta_id) y on a.bod_id=y.sta_id where a.bod_type_id=19 and a.bod_status_id=1 and a.comp_id=1  and a.carry_dt>= '2025-01-01' and a.carry_dt< dateadd(day,1,'2025-07-16')
 
 ) y on a.rec_id=y.rec_id


 select h.rec_id,b.dtl_id,a.bod_id,a.bod_type_id,a.busi_type,a.bod_cd,creat_dt=cast(convert(char(10),a.carry_dt,20) as datetime),a.bod_desc, d.type_id2,d.price1,b.price3, e.mate_name,mate_name1=f.mate_name, b.lead_id,leader=k.BU_SORT1,department=k.VKBUR_TXT,sta_id=case when h.sta_id is null then b.sta_id else h.sta_id end, broker=c.zname,cdistrict=dbo.fn_getdistrict1(e.district),receiver1=c.receiver,c.bank_name,c.depo_acco, b.med_id,m.material_code,m.med_code,m.med_name,m.specifi,m.pdt_place,med_unit=dbo.fn_obj_desc(m.unit_id),m.type_id1, b.bat_cd,amot=cast(d.rate*b.qty as decimal(15,2)), b.qty,rate=cast(d.rate as decimal(15,4)), rate2=cast(case when isnull(d.price1,0)=0 then 0 else 100.00*d.rate/d.price1 end as decimal(10,2)), y.ckd_amot,j.amot1,j.amot2,h.ckd_amot3 ,b.channel_id,channel=dbo.fn_obj_desc1(11,b.channel_id),b.channel_dtl_id,channel_dtl=dbo.fn_obj_desc1(12,b.channel_dtl_id) 
 from tb_bill a 
 inner join tb_bill_dtl b on a.bod_id=b.bod_id 
 left join tb_bill_stadtl h on b.dtl_id=h.dtl_id 
 left join tb_staff c on c.sta_id=case when h.sta_id is null then b.sta_id else h.sta_id end 
 inner join tb_busimate e on a.dst_id=e.mate_id 
 left  join tb_busimate f on a.src_id=f.mate_id 
 inner join tb_medicine m on b.med_id=m.med_id 
 left join (select i.rec_id,i.type_id2,i.price1,j.sta_id,j.rate from tb_brokermed i inner join tb_brokermedtl j on i.rec_id=j.rela_id) d on d.rec_id =dbo.fn_getbrokermedrecid(a.src_id,a.dst_id,b.med_id,a.carry_dt) and d.sta_id=h.sta_id 
 left join SAP_ZSD_BUS k on k.rec_id=dbo.fn_getSAP_ZSD_BUSrecid(b.channel_id,b.channel_dtl_id,e.district,e.mate_code,m.material_code1,a.carry_dt) 
 left join (select b.med_id,amot1=sum(cast(isnull(b.amot,0) as decimal(15,2))),amot2=sum(case a.bod_status_id when 1 then 1 else 0 end*cast(isnull(b.amot,0) as decimal(15,2))) from tb_bill a,tb_bill_dtl b where a.bod_type_id=17  and a.bod_id=b.bod_id and b.med_id>0 group by b.med_id) j on h.rec_id=j.med_id 
 left join (select b.med_id,ckd_amot=sum(cast(b.amot as decimal(15,2))) from tb_bill a,tb_bill_dtl b where a.bod_type_id=17 and a.bod_status_id=1  and a.bod_id=b.bod_id 	and exists (select 1 from tb_bill c,tb_bill_dtl d where c.bod_type_id=18 and c.bod_status_id=1 and c.creat_dt>= '2025-01-01' and c.bod_id=d.bod_id and d.med_id=a.bod_id) group by b.med_id) y on h.rec_id=y.med_id 
 where a.bod_type_id=2 and a.bod_status_id=1 and e.mate_type_id=1   and a.carry_dt>= '2025-01-01' and a.carry_dt< dateadd(day,1,'2025-07-16') and (h.rate<>0 or b.rate<>0) 
 union all 
 select h.rec_id,dtl_id=0,a.bod_id,a.bod_type_id,busi_type=0,a.bod_cd,creat_dt=cast(convert(char(10),a.carry_dt,20) as datetime),a.bod_desc, type_id2=0,price1=0,price3=0, mate_name=dbo.fn_mate_name(a.dst_id),mate_name1=f.mate_name, lead_id=0,leader='',department='',sta_id=a.broker_id,broker=c.zname,cdistrict=dbo.fn_getdistrict(c.district),receiver1=c.receiver,c.bank_name,c.depo_acco, a.med_id,m.material_code,m.med_code,m.med_name,m.specifi,m.pdt_place,med_unit=dbo.fn_obj_desc(m.unit_id),m.type_id1, bat_cd='',amot=cast(a.bod_amot as decimal(15,2)),qty=0,rate=0,rate2=0.00,y.ckd_amot,j.amot1,j.amot2,h.ckd_amot3 ,a.channel_id,channel=dbo.fn_obj_desc1(11,a.channel_id),a.channel_dtl_id,channel_dtl=dbo.fn_obj_desc1(12,a.channel_dtl_id) from tb_bill a left join tb_bill_stadtl h on a.bod_id=h.bod_id inner join tb_staff c on a.broker_id=c.sta_id left join tb_busimate f on a.src_id=f.mate_id left join tb_medicine m on a.med_id=m.med_id left join (select b.sta_id,amot1=sum(cast(isnull(b.amot,0) as decimal(15,2))),amot2=sum(case a.bod_status_id when 1 then 1 else 0 end*cast(isnull(b.amot,0) as decimal(15,2))) 	from tb_bill a,tb_bill_dtl b where a.bod_type_id=17  and a.bod_id=b.bod_id and b.sta_id>0 group by b.sta_id) j on a.bod_id=j.sta_id left join (select b.sta_id,ckd_amot=sum(b.amot) from tb_bill a,tb_bill_dtl b where a.bod_type_id=17 and a.bod_status_id=1 and a.creat_dt>= '2025-01-01'  and a.bod_id=b.bod_id 	and exists (select 1 from tb_bill c,tb_bill_dtl d where c.bod_type_id=18 and c.bod_status_id=1 and c.creat_dt>= '2025-01-01' and c.bod_id=d.bod_id and d.med_id=a.bod_id) group by b.sta_id) y on a.bod_id=y.sta_id where a.bod_type_id=19 and a.bod_status_id=1 and a.comp_id=1  and a.carry_dt>= '2025-01-01' and a.carry_dt< dateadd(day,1,'2025-07-16')
