truncate table tb_sysframe 

select * from tb_sysframe

insert into tb_sysframe (sf_parent,sf_title)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke)

insert into tb_sysframe (sf_parent,sf_title) values (-1,'系统设置')
insert into tb_sysframe (sf_parent,sf_title) values (-1,'药品管理')
insert into tb_sysframe (sf_parent,sf_title) values (-1,'业务管理')
insert into tb_sysframe (sf_parent,sf_title) values (-1,'商业管理')
insert into tb_sysframe (sf_parent,sf_title) values (-1,'商业结算')
insert into tb_sysframe (sf_parent,sf_title) values (-1,'分销管理')
insert into tb_sysframe (sf_parent,sf_title) values (-1,'分销结算')
insert into tb_sysframe (sf_parent,sf_title) values (-1,'新零售管理')
insert into tb_sysframe (sf_parent,sf_title) values (-1,'新零售结算')
insert into tb_sysframe (sf_parent,sf_title) values (-1,'综合资料')

insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (1,'设置员工 ',1)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (1,'设置用户权限 ',8)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (1,'业务设置 ',12)

insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (2,'设置药品',5)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (2,'设置药品中标价',277)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (2,'设置药品考核价',278)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (2,'设置学术标准政策',279)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (2,'设置分销标准政策',280)

insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (3,'设置渠道',97)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (3,'设置客户价格组',100)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (3,'设置业务员',2)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (3,'设置业务负责人',115)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (3,'设置商业公司',7)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (3,'设置客户(医院)',3)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (3,'设置推广服务商',281)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (3,'设置业务结构',53)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (3,'设置商业级别',52)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (3,'结账控制表',31)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (3,'流向词语对照',85)

insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (4,'商业采购入库单',10)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (4,'商业采购综合查询',14)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (4,'商业采购推广费统计',282)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (4,'商业销售出库单',11)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (4,'商业销售综合查询',15)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (4,'商业库存查询',13)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (4,'商业历史库存',86)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (4,'商业盘点单-制单',55)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (4,'商业盘点单-审核',176)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (4,'商业盘点单-综合查询',56)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (4,'品种流向查询',22)

insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (5,'业务员费用规则-规则表',41)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (5,'业务员费用规则-启用-业务申请',39)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (5,'业务员费用规则-启用-业务审核',40)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (5,'业务员费用规则-启用-财务复核',45)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (5,'业务员费用规则-启用-财务审批',58)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (5,'业务员费用规则-停用-业务申请',38)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (5,'业务员费用规则-停用-业务审核',43)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (5,'业务员费用规则-停用-财务复核',51)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (5,'业务员费用规则-停用-财务审批',59)

insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (5,'医院托管费规则-规则表',67)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (5,'医院托管费规则-启用-业务申请',72)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (5,'医院托管费规则-启用-业务审核',73)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (5,'医院托管费规则-启用-财务复核',74)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (5,'医院托管费规则-启用-财务审批',75)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (5,'医院托管费规则-停用-业务申请',81)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (5,'医院托管费规则-停用-业务审核',82)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (5,'医院托管费规则-停用-财务复核',83)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (5,'医院托管费规则-停用-财务审批',84)

insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (5,'业务员费用兑付-应付费用记账-制单',117)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (5,'业务员费用兑付-应付费用记账-审核',133)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (5,'业务员费用兑付-汇总',95)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (5,'业务员费用兑付-付款审批-业务申请',96)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (5,'业务员费用兑付-付款审批-财务复核',98)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (5,'业务员费用兑付-付款审批-财务审批',99)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (5,'业务员费用兑付-出纳付款-查询',101)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (5,'业务员费用兑付-出纳付款-制单',102)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (5,'业务员费用兑付-出纳付款-审核',103)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (5,'业务员费用兑付-费用补差表',283)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (5,'业务员费用兑付-费用补差单-制单',284)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (5,'业务员费用兑付-费用补差单-审核',285)

insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (6,'分销采购入库单',128)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (6,'分销采购综合查询',126)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (6,'分销销售出库单',129)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (6,'分销销售综合查询',127)

insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (7,'设置销售促销规则',169)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (7,'销售促销规则审批-财务申请',170)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (7,'销售促销规则审批-财务复核',171)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (7,'销售促销规则审批-财务审核',286)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (7,'分销销售促销规则明细表',287)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (7,'其他支出记账-制单',172)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (7,'其他支出记账-审批',173)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (7,'其他支出核销',174)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (7,'其他支出审批付款-付款审批-部门申请',175)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (7,'其他支出审批付款-付款审批-财务复核',177)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (7,'其他支出审批付款-付款审批-财务审核',178)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (7,'其他支出审批付款-出纳付款-查询',187)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (7,'其他支出审批付款-出纳付款-制单',179)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (7,'其他支出审批付款-出纳付款-审核',180)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (7,'其他支出收款单-制单',288)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (7,'其他支出收款单-审批',289)

insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (7,'分销返款汇总表',246)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (7,'分销客户对账表',291)

insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (8,'新零售商业采购入库',301)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (8,'新零售商业采购入库综合查询',302)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (8,'连锁终端销售出库单',303)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (8,'连锁终端销售出库综合查询',304)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (8,'零售销售出库单',305)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (8,'零售销售综合查询',306)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (8,'连锁终端盘点单-制单',307)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (8,'连锁终端盘点单-审核',308)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (8,'连锁终端库存查询',309)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (8,'进销存对比分析表',310)

insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (9,'设置购进费用政策',311)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (9,'新零售购进应付记账-制单',312)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (9,'新零售购进应付记账-审核',313)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (9,'购进费用核销',314)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (9,'购进费用审批付款-付款审批-部门申请',315)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (9,'购进费用审批付款-付款审批-财务复核',316)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (9,'购进费用审批付款-付款审批-财务审核',317)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (9,'购进费用审批付款-出纳付款-查询',318)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (9,'购进费用审批付款-出纳付款-制单',319)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (9,'购进费用审批付款-出纳付款-审核',320)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (9,'设置动销费用政策',321)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (9,'新零售动销应付记账-制单',322)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (9,'新零售动销应付记账-审核',323)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (9,'动销费用核销',324)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (9,'动销费用审批付款-付款审批-部门申请',325)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (9,'动销费用审批付款-付款审批-财务复核',326)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (9,'动销费用审批付款-付款审批-财务审核',327)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (9,'动销费用审批付款-出纳付款-查询',328)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (9,'动销费用审批付款-出纳付款-制单',329)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (9,'动销费用审批付款-出纳付款-审核',330)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (9,'新零售付款出纳查询',331)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (9,'新零告费用明细表',332)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (9,'新零告费用汇总表',333)

insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (10,'费用汇总表',247)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (10,'其他支出费用状态汇总报表',234)
insert into tb_sysframe (sf_parent,sf_title,sf_invoke) values (10,'Rx销售明细汇总报表',123)
